version: '3'
services:

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 1

  broker-service:
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    container_name: broker
    restart: always
    environment:
      LOKI_WEBHOOK_URL: "http://loki:3300"
      JAEGER_AGENT_HOST: "jaeger:6831"
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth
    restart: always
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      LOKI_WEBHOOK_URL: "http://loki:3300"
      JAEGER_AGENT_HOST: "jaeger:6831"
    ports:
      - 8081:80
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    container_name: "postgres"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./data/db-data/postgres/:/var/lib/postgresql/data/

  # Observability tools

  jaeger:
    image: jaegertracing/jaeger-agent
    container_name: jaeger
    ports:
      - "14268:14268"
      - "6831:6831"
      - "5778:5778"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    command: ["--reporter.grpc.host-port=otel:14250"]

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: "otel"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel/config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "55680:55680"

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
    depends_on:
      - tempo
      - loki

  tempo:
    image: grafana/tempo:latest
    container_name: "tempo"
    volumes:
      - ./config/tempo/tempo-local.yaml:/etc/tempo-local.yaml
    command: "-config.file=/etc/tempo-local.yaml"
    ports:
      - "3100:3100"
      - "3200:3200"

  loki:
    depends_on:
      - minio
    image: grafana/loki:latest
    container_name: "loki"
    ports:
      - "3300:3300"
    volumes:
      - ./config/loki/config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  minio:
    image: minio/minio:latest
    container_name: "minio"
    environment:
      MINIO_ROOT_USER: loki
      MINIO_ROOT_PASSWORD: supersecret
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
    command: server /data