apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://loki:3300
    access: proxy
    isDefault: true
    jsonData:
      maxLines: 1000

  - name: Tempo
    type: tempo
    url: http://tempo:3100
    access: proxy
