global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3100' ]
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    # only grab metrics with 'otelchi'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*otelchi.*'
        action: keep      